### ISSUE TITLE
Fix .gitignore

### ISSUE THREAD

**Issue by djkool** [sam0s/dungeon-farm#10]
`.gitignore` is showing up in the repo as `.gitignore.gitignore` and is not properly being used by git. As such, a lot of `*.pyc` files have crept into the repo and should be removed after `.gitignore` is renamed correctly.

```
git mv .gitignore.gitignore
git rm -rf *.pyc
```

**Comment by sam0s** [comment]
thats strange, i didnt even notice lol

**Comment by sam0s** [comment]
fixed!
