### ISSUE TITLE
Pathfinding!

### ISSUE THREAD

**Issue by sam0s** [sam0s/dungeon-farm#9]
Make it perfect?

**Comment by sam0s** [comment]
Currently works, but is a little janky.

**Comment by djkool** [comment]
Was leaving this open to make sure there wasn't any bugs with my implementation. Things have been running smooth for a bit. I'm going to close it after I add one last feature:

- [ ] Allow for destination changes while following existing path.

**Comment by sam0s** [comment]
awesome!
